### ISSUE TITLE
Curl headers in http client are set incorrect

### ISSUE THREAD

**Issue by oskarcafe** [marcelklehr/tivoka#48]
When creating the headers passed to curl_setopt($ch, CURLOPT_HTTPHEADER, $headers), new lines are appended to each header value. This was introduced in commit 2caa7599fbe6472a0a36559f3656256236b6830d in Http.php on line 96 when building support for curl requests:

```
foreach($this->headers as $label => $value) {
  $headers[] = $label . ": " . $value . "\r\n";
}
```

According to the curl_setopt() documentation for option CURLOPT_HTTPHEADER at http://php.net/manual/en/function.curl-setopt.php, the array values should not include the trailing new line.

The effect is that the http body is prepended with \r\n which modifies the body content, which can be fatal and very hard to find when debugging.

Removing the "\r\n" should do it and has been confirmed by our own testing. The correct line should look like:

`$headers[] = $label . ": " . $value;`

**Comment by marcelklehr** [comment]
Nice catch!

**Comment by oskarcafe** [comment]
Thanks for quick fix and great software!
