### ISSUE TITLE
Method names conflict

### ISSUE THREAD

**Issue by xsqox** [marcelklehr/tivoka#49]
I created a method called 'register' and it was not working properly probably because of the conflict with system method that registers user-defined methods.

Conflict case:
$methods = array(
'register' => function($params) {
        list($email, $username, $pass) = $params;
        return $email;
}
)

After renaming the method to 'user_register', it started to work.

**Comment by marcelklehr** [comment]
Good catch, will sort ASAP

**Comment by marcelklehr** [comment]
ASAP > 1year, heh. I've been busy :)
